#include "generator.h"

#include <base/logger.h>
#include <base/str.h>
#include <base/system.h>

#include <engine/shared/datafile.h>
#include <engine/shared/map.h>
#include <engine/storage.h>

#include <game/gamecore.h>
#include <game/mapitems.h>

#include <algorithm>
#include <array>
#include <memory>
#include <numeric>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

namespace
{
constexpr const char *TOOL_NAME = "map_generator";
constexpr int DEFAULT_WIDTH = 50;
constexpr int DEFAULT_HEIGHT = 20;
constexpr int MIN_WIDTH = 8;
constexpr int MIN_HEIGHT = 6;
constexpr int DEFAULT_GAP_EXTRA = 4;
constexpr int DEFAULT_KEEP_EVERY = 2;
constexpr const char *DEFAULT_AUTHOR = "QmClient map_generator";
constexpr const char *DEFAULT_MAP_VERSION = "1";
constexpr const char *DEFAULT_CREDITS = "Generated by QmClient map_generator";
constexpr const char *DEFAULT_LICENSE = "CC0-1.0";
constexpr const char *GROUP_NAME = "Game";
constexpr const char *GAME_LAYER_NAME = "Game";
constexpr const char *FRONT_LAYER_NAME = "Front";

struct CGeneratorConfig
{
	std::string m_OutputPath;
	std::string m_SourceMapPath;
	int m_Width = DEFAULT_WIDTH;
	int m_Height = DEFAULT_HEIGHT;
	int m_GapExtra = DEFAULT_GAP_EXTRA;
	int m_KeepEvery = DEFAULT_KEEP_EVERY;
	std::string m_Author = DEFAULT_AUTHOR;
	std::string m_MapVersion = DEFAULT_MAP_VERSION;
	std::string m_Credits = DEFAULT_CREDITS;
	std::string m_License = DEFAULT_LICENSE;
};

struct CTileLayerData
{
	bool m_Present = false;
	int m_Width = 0;
	int m_Height = 0;
	std::string m_Name;
	std::vector<CTile> m_vTiles;
};

struct CSourceMapData
{
	std::string m_Author;
	std::string m_MapVersion;
	std::string m_Credits;
	std::string m_License;
	CTileLayerData m_GameLayer;
	CTileLayerData m_FrontLayer;
};

struct CColumnSegment
{
	int m_Start = 0;
	int m_End = 0;
	bool m_HasAnchor = false;

	int Width() const
	{
		return m_End - m_Start + 1;
	}
};

enum class EParseResult
{
	Success,
	Help,
	Error,
};

enum class EProgressAxis
{
	Horizontal,
	Vertical,
};

struct CAnchorInfo
{
	std::optional<ivec2> m_Spawn;
	std::optional<ivec2> m_Start;
	std::optional<ivec2> m_Finish;
};

int EncodeTile(const CTile &Tile);
CTile DecodeTile(int Encoded);

void PrintUsage()
{
	log_info(TOOL_NAME, "Usage: %s <output.map> [options]", TOOL_NAME);
	log_info(TOOL_NAME, "Options:");
	log_info(TOOL_NAME, "  --width <number>        New skeleton map width in tiles (default: %d)", DEFAULT_WIDTH);
	log_info(TOOL_NAME, "  --height <number>       New skeleton map height in tiles (default: %d)", DEFAULT_HEIGHT);
	log_info(TOOL_NAME, "  --source-map <path>     Read an existing map and generate a shortened gameplay-only version");
	log_info(TOOL_NAME, "  --gap-extra <number>    Extra empty columns inserted between kept obstacle chunks (default: %d)", DEFAULT_GAP_EXTRA);
	log_info(TOOL_NAME, "  --keep-every <number>   Keep every Nth middle obstacle chunk while shortening (default: %d)", DEFAULT_KEEP_EVERY);
	log_info(TOOL_NAME, "  --author <text>         Map author string");
	log_info(TOOL_NAME, "  --map-version <text>    Map version string");
	log_info(TOOL_NAME, "  --credits <text>        Map credits string");
	log_info(TOOL_NAME, "  --license <text>        Map license string");
	log_info(TOOL_NAME, "  --help                  Show this help");
	log_info(TOOL_NAME, "Without --source-map the tool creates a small gameplay skeleton.");
	log_info(TOOL_NAME, "With --source-map it keeps game/front physics only, shortens the route and increases the gaps between kept obstacle chunks.");
}

bool ParsePositiveInt(const char *pName, const char *pValue, int Minimum, int &OutValue)
{
	int Value = 0;
	if(!str_toint(pValue, &Value))
	{
		log_error(TOOL_NAME, "Invalid value for %s: '%s' is not a number", pName, pValue);
		return false;
	}
	if(Value < Minimum)
	{
		log_error(TOOL_NAME, "Invalid value for %s: %d is smaller than %d", pName, Value, Minimum);
		return false;
	}
	OutValue = Value;
	return true;
}

bool ReadOptionValue(int argc, const char **argv, int &Index, const char *pOption, const char **ppValue)
{
	if(Index + 1 >= argc)
	{
		log_error(TOOL_NAME, "Missing value after %s", pOption);
		return false;
	}
	*ppValue = argv[++Index];
	return true;
}

bool IsAbsolutePath(const char *pPath)
{
	if(!pPath || pPath[0] == '\0')
		return false;
	if(pPath[0] == '/' || pPath[0] == '\\')
		return true;
	return str_length(pPath) >= 2 && pPath[1] == ':';
}

EParseResult ParseArguments(int argc, const char **argv, CGeneratorConfig &OutConfig)
{
	if(argc <= 1)
	{
		PrintUsage();
		return EParseResult::Help;
	}

	for(int Index = 1; Index < argc; ++Index)
	{
		const char *pArgument = argv[Index];
		if(str_comp(pArgument, "--help") == 0 || str_comp(pArgument, "-h") == 0)
		{
			PrintUsage();
			return EParseResult::Help;
		}
		if(str_comp(pArgument, "--width") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue) || !ParsePositiveInt("--width", pValue, MIN_WIDTH, OutConfig.m_Width))
				return EParseResult::Error;
			continue;
		}
		if(str_comp(pArgument, "--height") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue) || !ParsePositiveInt("--height", pValue, MIN_HEIGHT, OutConfig.m_Height))
				return EParseResult::Error;
			continue;
		}
		if(str_comp(pArgument, "--gap-extra") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue) || !ParsePositiveInt("--gap-extra", pValue, 0, OutConfig.m_GapExtra))
				return EParseResult::Error;
			continue;
		}
		if(str_comp(pArgument, "--keep-every") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue) || !ParsePositiveInt("--keep-every", pValue, 1, OutConfig.m_KeepEvery))
				return EParseResult::Error;
			continue;
		}
		if(str_comp(pArgument, "--source-map") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue))
				return EParseResult::Error;
			OutConfig.m_SourceMapPath = pValue;
			continue;
		}
		if(str_comp(pArgument, "--author") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue))
				return EParseResult::Error;
			OutConfig.m_Author = pValue;
			continue;
		}
		if(str_comp(pArgument, "--map-version") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue))
				return EParseResult::Error;
			OutConfig.m_MapVersion = pValue;
			continue;
		}
		if(str_comp(pArgument, "--credits") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue))
				return EParseResult::Error;
			OutConfig.m_Credits = pValue;
			continue;
		}
		if(str_comp(pArgument, "--license") == 0)
		{
			const char *pValue = nullptr;
			if(!ReadOptionValue(argc, argv, Index, pArgument, &pValue))
				return EParseResult::Error;
			OutConfig.m_License = pValue;
			continue;
		}
		if(str_startswith(pArgument, "--") != nullptr)
		{
			log_error(TOOL_NAME, "Unknown option: %s", pArgument);
			return EParseResult::Error;
		}
		if(!OutConfig.m_OutputPath.empty())
		{
			log_error(TOOL_NAME, "Only one output path is supported, got extra argument: %s", pArgument);
			return EParseResult::Error;
		}
		OutConfig.m_OutputPath = pArgument;
	}

	if(OutConfig.m_OutputPath.empty())
	{
		log_error(TOOL_NAME, "Missing output path");
		return EParseResult::Error;
	}

	const char *pFilename = fs_filename(OutConfig.m_OutputPath.c_str());
	char aExtension[64];
	fs_split_file_extension(pFilename, nullptr, 0, aExtension, sizeof(aExtension));
	if(aExtension[0] == '\0')
	{
		OutConfig.m_OutputPath += ".map";
	}
	else if(str_endswith_nocase(pFilename, ".map") == nullptr)
	{
		log_error(TOOL_NAME, "Output path must end with .map, got '%s'", OutConfig.m_OutputPath.c_str());
		return EParseResult::Error;
	}

	return EParseResult::Success;
}

CTile MakeTile(unsigned char Index)
{
	CTile Tile{};
	Tile.m_Index = Index;
	return Tile;
}

bool IsAir(const CTile &Tile)
{
	return Tile.m_Index == TILE_AIR;
}

bool IsAnchorTile(const CTile &Tile)
{
	return Tile.m_Index == TILE_START ||
		Tile.m_Index == TILE_FINISH ||
		Tile.m_Index == ENTITY_OFFSET + ENTITY_SPAWN ||
		Tile.m_Index == ENTITY_OFFSET + ENTITY_SPAWN_RED ||
		Tile.m_Index == ENTITY_OFFSET + ENTITY_SPAWN_BLUE;
}

const CTile &GetTile(const CTileLayerData &Layer, int X, int Y)
{
	dbg_assert(Layer.m_Present, "Layer missing");
	dbg_assert(X >= 0 && X < Layer.m_Width, "Tile X out of bounds");
	dbg_assert(Y >= 0 && Y < Layer.m_Height, "Tile Y out of bounds");
	return Layer.m_vTiles[(size_t)Y * Layer.m_Width + X];
}

void SetTile(std::vector<CTile> &vTiles, int Width, int Height, int X, int Y, const CTile &Tile)
{
	dbg_assert(X >= 0 && X < Width, "Tile X out of bounds");
	dbg_assert(Y >= 0 && Y < Height, "Tile Y out of bounds");
	vTiles[(size_t)Y * Width + X] = Tile;
}

void SetTile(std::vector<CTile> &vTiles, int Width, int Height, int X, int Y, unsigned char Index)
{
	SetTile(vTiles, Width, Height, X, Y, MakeTile(Index));
}

std::vector<CTile> CreateGameLayerTiles(const CGeneratorConfig &Config)
{
	std::vector<CTile> vTiles((size_t)Config.m_Width * Config.m_Height, MakeTile(TILE_AIR));

	for(int X = 0; X < Config.m_Width; ++X)
	{
		SetTile(vTiles, Config.m_Width, Config.m_Height, X, 0, TILE_SOLID);
		SetTile(vTiles, Config.m_Width, Config.m_Height, X, Config.m_Height - 1, TILE_SOLID);
	}
	for(int Y = 0; Y < Config.m_Height; ++Y)
	{
		SetTile(vTiles, Config.m_Width, Config.m_Height, 0, Y, TILE_SOLID);
		SetTile(vTiles, Config.m_Width, Config.m_Height, Config.m_Width - 1, Y, TILE_SOLID);
	}

	const int WalkwayY = Config.m_Height - 2;
	SetTile(vTiles, Config.m_Width, Config.m_Height, 2, WalkwayY, ENTITY_OFFSET + ENTITY_SPAWN);
	SetTile(vTiles, Config.m_Width, Config.m_Height, 3, WalkwayY, TILE_START);
	SetTile(vTiles, Config.m_Width, Config.m_Height, Config.m_Width - 4, WalkwayY, TILE_FINISH);

	return vTiles;
}

bool PrepareOutputPath(IStorage &Storage, const char *pOutputPath, int StorageType, char *pFullPath, size_t FullPathSize)
{
	if(StorageType == IStorage::TYPE_ABSOLUTE)
	{
		str_copy(pFullPath, pOutputPath, FullPathSize);
	}
	else
	{
		Storage.GetCompletePath(StorageType, pOutputPath, pFullPath, FullPathSize);
	}
	if(fs_makedir_rec_for(pFullPath) < 0)
	{
		log_error(TOOL_NAME, "Failed to create parent directory for '%s'", pFullPath);
		return false;
	}
	return true;
}

std::optional<std::string> ReadMapString(CDataFileReader &Reader, int Index)
{
	if(Index < 0)
		return std::string();
	const char *pValue = Reader.GetDataString(Index);
	if(!pValue)
		return std::nullopt;
	return std::string(pValue);
}

bool LoadTileLayer(CDataFileReader &Reader, const CMapItemLayerTilemap *pTilemapItem, int DataIndex, CTileLayerData &OutLayer)
{
	if(pTilemapItem->m_Width <= 0 || pTilemapItem->m_Height <= 0)
	{
		log_error(TOOL_NAME, "Invalid tile layer size %dx%d", pTilemapItem->m_Width, pTilemapItem->m_Height);
		return false;
	}

	void *pData = Reader.GetData(DataIndex);
	const int DataSize = Reader.GetDataSize(DataIndex);
	if(pData == nullptr || DataSize <= 0 || DataSize % (int)sizeof(CTile) != 0)
	{
		log_error(TOOL_NAME, "Failed to read tile layer payload");
		return false;
	}

	OutLayer.m_Present = true;
	OutLayer.m_Width = pTilemapItem->m_Width;
	OutLayer.m_Height = pTilemapItem->m_Height;
	OutLayer.m_vTiles.assign((size_t)OutLayer.m_Width * OutLayer.m_Height, MakeTile(TILE_AIR));
	CMap::ExtractTiles(OutLayer.m_vTiles.data(), OutLayer.m_vTiles.size(), static_cast<const CTile *>(pData), (size_t)DataSize / sizeof(CTile));

	char aName[16] = "";
	if(pTilemapItem->m_Version >= 3)
		IntsToStr(pTilemapItem->m_aName, std::size(pTilemapItem->m_aName), aName, sizeof(aName));
	OutLayer.m_Name = aName;

	Reader.UnloadData(DataIndex);
	return true;
}

bool LoadSourceMap(const CGeneratorConfig &Config, IStorage &Storage, CSourceMapData &OutMap)
{
	const int SourceStorageType = IsAbsolutePath(Config.m_SourceMapPath.c_str()) ? IStorage::TYPE_ABSOLUTE : IStorage::TYPE_ALL;

	CDataFileReader Reader;
	if(!Reader.Open(&Storage, Config.m_SourceMapPath.c_str(), SourceStorageType))
	{
		log_error(TOOL_NAME, "Failed to open source map '%s'", Config.m_SourceMapPath.c_str());
		return false;
	}

	const CMapItemVersion *pVersion = static_cast<CMapItemVersion *>(Reader.FindItem(MAPITEMTYPE_VERSION, 0));
	if(pVersion == nullptr || pVersion->m_Version != 1)
	{
		log_error(TOOL_NAME, "Unsupported source map version in '%s'", Config.m_SourceMapPath.c_str());
		Reader.Close();
		return false;
	}

	const CMapItemInfoSettings *pInfo = static_cast<const CMapItemInfoSettings *>(Reader.FindItem(MAPITEMTYPE_INFO, 0));
	if(pInfo != nullptr)
	{
		if(const auto Author = ReadMapString(Reader, pInfo->m_Author); Author.has_value())
			OutMap.m_Author = *Author;
		if(const auto MapVersion = ReadMapString(Reader, pInfo->m_MapVersion); MapVersion.has_value())
			OutMap.m_MapVersion = *MapVersion;
		if(const auto Credits = ReadMapString(Reader, pInfo->m_Credits); Credits.has_value())
			OutMap.m_Credits = *Credits;
		if(const auto License = ReadMapString(Reader, pInfo->m_License); License.has_value())
			OutMap.m_License = *License;
	}

	int GroupsStart = 0;
	int GroupsNum = 0;
	int LayersStart = 0;
	int LayersNum = 0;
	Reader.GetType(MAPITEMTYPE_GROUP, &GroupsStart, &GroupsNum);
	Reader.GetType(MAPITEMTYPE_LAYER, &LayersStart, &LayersNum);

	for(int GroupIndex = 0; GroupIndex < GroupsNum; ++GroupIndex)
	{
		const CMapItemGroup *pGroup = static_cast<const CMapItemGroup *>(Reader.GetItem(GroupsStart + GroupIndex));
		if(!pGroup)
			continue;

		for(int LayerIndex = 0; LayerIndex < pGroup->m_NumLayers; ++LayerIndex)
		{
			const int AbsoluteLayerIndex = LayersStart + pGroup->m_StartLayer + LayerIndex;
			if(AbsoluteLayerIndex < LayersStart || AbsoluteLayerIndex >= LayersStart + LayersNum)
				continue;

			const CMapItemLayer *pLayer = static_cast<const CMapItemLayer *>(Reader.GetItem(AbsoluteLayerIndex));
			if(!pLayer || pLayer->m_Type != LAYERTYPE_TILES)
				continue;

			const CMapItemLayerTilemap *pTilemap = reinterpret_cast<const CMapItemLayerTilemap *>(pLayer);
			if((pTilemap->m_Flags & TILESLAYERFLAG_GAME) != 0)
			{
				if(OutMap.m_GameLayer.m_Present)
					continue;
				if(!LoadTileLayer(Reader, pTilemap, pTilemap->m_Data, OutMap.m_GameLayer))
				{
					Reader.Close();
					return false;
				}
			}
			else if((pTilemap->m_Flags & TILESLAYERFLAG_FRONT) != 0)
			{
				if(OutMap.m_FrontLayer.m_Present)
					continue;
				int FrontData = pTilemap->m_Front;
				if(pTilemap->m_Version <= 2)
					FrontData = *((const int *)(pTilemap) + 17);
				if(!LoadTileLayer(Reader, pTilemap, FrontData, OutMap.m_FrontLayer))
				{
					Reader.Close();
					return false;
				}
			}
		}
	}

	Reader.Close();

	if(!OutMap.m_GameLayer.m_Present)
	{
		log_error(TOOL_NAME, "Source map has no game layer");
		return false;
	}
	if(OutMap.m_FrontLayer.m_Present &&
		(OutMap.m_FrontLayer.m_Width != OutMap.m_GameLayer.m_Width || OutMap.m_FrontLayer.m_Height != OutMap.m_GameLayer.m_Height))
	{
		log_error(TOOL_NAME, "Game/front layer size mismatch in source map");
		return false;
	}

	if(OutMap.m_GameLayer.m_Name.empty())
		OutMap.m_GameLayer.m_Name = GAME_LAYER_NAME;
	if(OutMap.m_FrontLayer.m_Present && OutMap.m_FrontLayer.m_Name.empty())
		OutMap.m_FrontLayer.m_Name = FRONT_LAYER_NAME;

	return true;
}

const CTile &GetTileOnAxis(const CTileLayerData &Layer, EProgressAxis Axis, int MainIndex, int CrossIndex)
{
	const int X = Axis == EProgressAxis::Horizontal ? MainIndex : CrossIndex;
	const int Y = Axis == EProgressAxis::Horizontal ? CrossIndex : MainIndex;
	return GetTile(Layer, X, Y);
}

void SetTileOnAxis(std::vector<CTile> &vTiles, int Width, int Height, EProgressAxis Axis, int MainIndex, int CrossIndex, const CTile &Tile)
{
	const int X = Axis == EProgressAxis::Horizontal ? MainIndex : CrossIndex;
	const int Y = Axis == EProgressAxis::Horizontal ? CrossIndex : MainIndex;
	SetTile(vTiles, Width, Height, X, Y, Tile);
}

int MainAxisLength(const CTileLayerData &Layer, EProgressAxis Axis)
{
	return Axis == EProgressAxis::Horizontal ? Layer.m_Width : Layer.m_Height;
}

int CrossAxisLength(const CTileLayerData &Layer, EProgressAxis Axis)
{
	return Axis == EProgressAxis::Horizontal ? Layer.m_Height : Layer.m_Width;
}

CAnchorInfo FindAnchors(const CSourceMapData &Source)
{
	CAnchorInfo Anchors;
	for(int Y = 0; Y < Source.m_GameLayer.m_Height; ++Y)
	{
		for(int X = 0; X < Source.m_GameLayer.m_Width; ++X)
		{
			const auto CheckTile = [&](const CTile &Tile) {
				if(Tile.m_Index == ENTITY_OFFSET + ENTITY_SPAWN ||
					Tile.m_Index == ENTITY_OFFSET + ENTITY_SPAWN_RED ||
					Tile.m_Index == ENTITY_OFFSET + ENTITY_SPAWN_BLUE)
				{
					if(!Anchors.m_Spawn.has_value())
						Anchors.m_Spawn = ivec2(X, Y);
				}
				else if(Tile.m_Index == TILE_START)
				{
					if(!Anchors.m_Start.has_value())
						Anchors.m_Start = ivec2(X, Y);
				}
				else if(Tile.m_Index == TILE_FINISH)
				{
					if(!Anchors.m_Finish.has_value())
						Anchors.m_Finish = ivec2(X, Y);
				}
			};

			CheckTile(GetTile(Source.m_GameLayer, X, Y));
			if(Source.m_FrontLayer.m_Present)
				CheckTile(GetTile(Source.m_FrontLayer, X, Y));
		}
	}

	if(!Anchors.m_Start.has_value() && Anchors.m_Spawn.has_value())
		Anchors.m_Start = Anchors.m_Spawn;
	return Anchors;
}

EProgressAxis DetectProgressAxis(const CSourceMapData &Source, const CAnchorInfo &Anchors)
{
	if(Anchors.m_Start.has_value() && Anchors.m_Finish.has_value())
	{
		const int Dx = Anchors.m_Finish->x - Anchors.m_Start->x;
		const int Dy = Anchors.m_Finish->y - Anchors.m_Start->y;
		const int AbsDx = Dx < 0 ? -Dx : Dx;
		const int AbsDy = Dy < 0 ? -Dy : Dy;
		return AbsDx >= AbsDy ? EProgressAxis::Horizontal : EProgressAxis::Vertical;
	}
	return Source.m_GameLayer.m_Width >= Source.m_GameLayer.m_Height ? EProgressAxis::Horizontal : EProgressAxis::Vertical;
}

int CountNonAirOnAxisSlice(const CSourceMapData &Source, EProgressAxis Axis, int MainIndex, const std::vector<bool> &vIgnoredCrossLines)
{
	const int Cross = CrossAxisLength(Source.m_GameLayer, Axis);
	int Count = 0;
	for(int CrossIndex = 0; CrossIndex < Cross; ++CrossIndex)
	{
		if(vIgnoredCrossLines[CrossIndex])
			continue;
		if(!IsAir(GetTileOnAxis(Source.m_GameLayer, Axis, MainIndex, CrossIndex)))
			++Count;
		if(Source.m_FrontLayer.m_Present && !IsAir(GetTileOnAxis(Source.m_FrontLayer, Axis, MainIndex, CrossIndex)))
			++Count;
	}
	return Count;
}

bool AxisSliceHasAnchor(const CSourceMapData &Source, EProgressAxis Axis, int MainIndex)
{
	const int Cross = CrossAxisLength(Source.m_GameLayer, Axis);
	for(int CrossIndex = 0; CrossIndex < Cross; ++CrossIndex)
	{
		if(IsAnchorTile(GetTileOnAxis(Source.m_GameLayer, Axis, MainIndex, CrossIndex)))
			return true;
		if(Source.m_FrontLayer.m_Present && IsAnchorTile(GetTileOnAxis(Source.m_FrontLayer, Axis, MainIndex, CrossIndex)))
			return true;
	}
	return false;
}

std::vector<bool> DetectBaselineCrossLines(const CSourceMapData &Source, EProgressAxis Axis)
{
	const int Main = MainAxisLength(Source.m_GameLayer, Axis);
	const int Cross = CrossAxisLength(Source.m_GameLayer, Axis);
	std::vector<bool> vBaseline(Cross, false);
	for(int CrossIndex = 0; CrossIndex < Cross; ++CrossIndex)
	{
		int Occupied = 0;
		for(int MainIndex = 0; MainIndex < Main; ++MainIndex)
		{
			if(!IsAir(GetTileOnAxis(Source.m_GameLayer, Axis, MainIndex, CrossIndex)) ||
				(Source.m_FrontLayer.m_Present && !IsAir(GetTileOnAxis(Source.m_FrontLayer, Axis, MainIndex, CrossIndex))))
			{
				++Occupied;
			}
		}
		if(Occupied * 10 >= Main * 6)
			vBaseline[CrossIndex] = true;
	}
	return vBaseline;
}

std::vector<CTile> BuildBaselineFillOnAxis(const CTileLayerData &Layer, EProgressAxis Axis, int NewMainLength, int OutputWidth, int OutputHeight, const std::vector<bool> &vBaselineCrossLines)
{
	std::vector<CTile> vFilled((size_t)OutputWidth * OutputHeight, MakeTile(TILE_AIR));
	if(!Layer.m_Present)
		return vFilled;

	const int Main = MainAxisLength(Layer, Axis);
	const int Cross = CrossAxisLength(Layer, Axis);
	for(int CrossIndex = 0; CrossIndex < Cross; ++CrossIndex)
	{
		if(!vBaselineCrossLines[CrossIndex])
			continue;

		std::unordered_map<int, int> Counts;
		for(int MainIndex = 0; MainIndex < Main; ++MainIndex)
		{
			const CTile &Tile = GetTileOnAxis(Layer, Axis, MainIndex, CrossIndex);
			if(IsAir(Tile))
				continue;
			Counts[EncodeTile(Tile)]++;
		}

		if(Counts.empty())
			continue;

		const auto Best = std::max_element(Counts.begin(), Counts.end(), [](const auto &Lhs, const auto &Rhs) {
			return Lhs.second < Rhs.second;
		});
		const CTile FillTile = DecodeTile(Best->first);
		for(int MainIndex = 0; MainIndex < NewMainLength; ++MainIndex)
			SetTileOnAxis(vFilled, OutputWidth, OutputHeight, Axis, MainIndex, CrossIndex, FillTile);
	}

	return vFilled;
}

std::vector<CColumnSegment> BuildSegmentsFromMask(const std::vector<bool> &vMask, const std::vector<bool> &vAnchors)
{
	std::vector<CColumnSegment> vSegments;
	for(int Index = 0; Index < (int)vMask.size(); ++Index)
	{
		if(!vMask[Index])
			continue;
		CColumnSegment Segment;
		Segment.m_Start = Index;
		while(Index + 1 < (int)vMask.size() && vMask[Index + 1])
			++Index;
		Segment.m_End = Index;
		for(int Slice = Segment.m_Start; Slice <= Segment.m_End; ++Slice)
			Segment.m_HasAnchor = Segment.m_HasAnchor || vAnchors[Slice];
		vSegments.push_back(Segment);
	}
	return vSegments;
}

std::vector<CColumnSegment> FindObstacleSegmentsOnAxis(const CSourceMapData &Source, EProgressAxis Axis, const std::vector<bool> &vBaselineCrossLines)
{
	const int Main = MainAxisLength(Source.m_GameLayer, Axis);
	std::vector<int> vDensity(Main, 0);
	std::vector<bool> vAnchors(Main, false);
	for(int MainIndex = 0; MainIndex < Main; ++MainIndex)
	{
		vDensity[MainIndex] = CountNonAirOnAxisSlice(Source, Axis, MainIndex, vBaselineCrossLines);
		vAnchors[MainIndex] = AxisSliceHasAnchor(Source, Axis, MainIndex);
	}

	std::vector<int> vPositiveDensity;
	for(int Density : vDensity)
	{
		if(Density > 0)
			vPositiveDensity.push_back(Density);
	}
	const int AverageDensity = vPositiveDensity.empty() ? 0 : std::accumulate(vPositiveDensity.begin(), vPositiveDensity.end(), 0) / (int)vPositiveDensity.size();

	std::vector<CColumnSegment> vBestSegments;
	for(int Divisor : {3, 2, 1})
	{
		const int Threshold = Divisor > 0 ? std::max(0, AverageDensity / Divisor) : 0;
		std::vector<bool> vMask(Main, false);
		for(int MainIndex = 0; MainIndex < Main; ++MainIndex)
			vMask[MainIndex] = vDensity[MainIndex] > Threshold || vAnchors[MainIndex];

		if(std::none_of(vMask.begin(), vMask.end(), [](bool Value) { return Value; }))
		{
			for(int MainIndex = 0; MainIndex < Main; ++MainIndex)
				vMask[MainIndex] = vDensity[MainIndex] > 0 || vAnchors[MainIndex];
		}

		std::vector<bool> vDilated = vMask;
		for(int MainIndex = 0; MainIndex < Main; ++MainIndex)
		{
			if(!vMask[MainIndex])
				continue;
			if(MainIndex > 0)
				vDilated[MainIndex - 1] = true;
			if(MainIndex + 1 < Main)
				vDilated[MainIndex + 1] = true;
		}

		std::vector<CColumnSegment> vSegments = BuildSegmentsFromMask(vDilated, vAnchors);
		if(vSegments.size() > vBestSegments.size())
			vBestSegments = vSegments;
		if(vSegments.size() > 1)
			return vSegments;
	}

	if(!vBestSegments.empty())
		return vBestSegments;

	std::vector<bool> vFallback(Main, true);
	return BuildSegmentsFromMask(vFallback, vAnchors);
}

void OverlayAxisSegment(std::vector<CTile> &vDestination, int OutputWidth, int OutputHeight, const CTileLayerData &SourceLayer, EProgressAxis Axis, const CColumnSegment &Segment, int DestinationMainStart)
{
	const int Cross = CrossAxisLength(SourceLayer, Axis);
	for(int SourceMain = Segment.m_Start; SourceMain <= Segment.m_End; ++SourceMain)
	{
		const int DestinationMain = DestinationMainStart + (SourceMain - Segment.m_Start);
		for(int CrossIndex = 0; CrossIndex < Cross; ++CrossIndex)
		{
			SetTileOnAxis(vDestination, OutputWidth, OutputHeight, Axis, DestinationMain, CrossIndex, GetTileOnAxis(SourceLayer, Axis, SourceMain, CrossIndex));
		}
	}
}

bool ColumnHasAnyNonAir(const CSourceMapData &Source, int X, const std::vector<bool> &vIgnoredRows)
{
	for(int Y = 0; Y < Source.m_GameLayer.m_Height; ++Y)
	{
		if(!vIgnoredRows.empty() && vIgnoredRows[Y])
			continue;
		if(!IsAir(GetTile(Source.m_GameLayer, X, Y)))
			return true;
		if(Source.m_FrontLayer.m_Present && !IsAir(GetTile(Source.m_FrontLayer, X, Y)))
			return true;
	}
	return false;
}

bool ColumnHasAnchor(const CSourceMapData &Source, int X)
{
	for(int Y = 0; Y < Source.m_GameLayer.m_Height; ++Y)
	{
		if(IsAnchorTile(GetTile(Source.m_GameLayer, X, Y)))
			return true;
		if(Source.m_FrontLayer.m_Present && IsAnchorTile(GetTile(Source.m_FrontLayer, X, Y)))
			return true;
	}
	return false;
}

int EncodeTile(const CTile &Tile)
{
	return Tile.m_Index |
		(static_cast<int>(Tile.m_Flags) << 8) |
		(static_cast<int>(Tile.m_Skip) << 16) |
		(static_cast<int>(Tile.m_Reserved) << 24);
}

CTile DecodeTile(int Encoded)
{
	CTile Tile{};
	Tile.m_Index = Encoded & 0xff;
	Tile.m_Flags = (Encoded >> 8) & 0xff;
	Tile.m_Skip = (Encoded >> 16) & 0xff;
	Tile.m_Reserved = (Encoded >> 24) & 0xff;
	return Tile;
}

std::vector<bool> DetectBaselineRows(const CSourceMapData &Source)
{
	std::vector<bool> vRows(Source.m_GameLayer.m_Height, false);
	for(int Y = 0; Y < Source.m_GameLayer.m_Height; ++Y)
	{
		int OccupiedColumns = 0;
		for(int X = 0; X < Source.m_GameLayer.m_Width; ++X)
		{
			if(!IsAir(GetTile(Source.m_GameLayer, X, Y)) || (Source.m_FrontLayer.m_Present && !IsAir(GetTile(Source.m_FrontLayer, X, Y))))
				++OccupiedColumns;
		}
		if(OccupiedColumns * 10 >= Source.m_GameLayer.m_Width * 6)
			vRows[Y] = true;
	}
	return vRows;
}

std::vector<CTile> BuildBaselineFill(const CTileLayerData &Layer, int NewWidth, const std::vector<bool> &vBaselineRows)
{
	std::vector<CTile> vFilled((size_t)NewWidth * Layer.m_Height, MakeTile(TILE_AIR));
	if(!Layer.m_Present)
		return vFilled;

	for(int Y = 0; Y < Layer.m_Height; ++Y)
	{
		if(!vBaselineRows[Y])
			continue;

		std::unordered_map<int, int> Counts;
		for(int X = 0; X < Layer.m_Width; ++X)
		{
			const CTile &Tile = GetTile(Layer, X, Y);
			if(IsAir(Tile))
				continue;
			Counts[EncodeTile(Tile)]++;
		}

		if(Counts.empty())
			continue;

		const auto Best = std::max_element(Counts.begin(), Counts.end(), [](const auto &Lhs, const auto &Rhs) {
			return Lhs.second < Rhs.second;
		});
		const CTile FillTile = DecodeTile(Best->first);
		for(int X = 0; X < NewWidth; ++X)
			SetTile(vFilled, NewWidth, Layer.m_Height, X, Y, FillTile);
	}

	return vFilled;
}

std::vector<CColumnSegment> FindObstacleSegments(const CSourceMapData &Source, const std::vector<bool> &vBaselineRows)
{
	std::vector<bool> vInterestingColumns(Source.m_GameLayer.m_Width, false);
	std::vector<bool> vAnchorColumns(Source.m_GameLayer.m_Width, false);
	for(int X = 0; X < Source.m_GameLayer.m_Width; ++X)
	{
		vInterestingColumns[X] = ColumnHasAnyNonAir(Source, X, vBaselineRows);
		vAnchorColumns[X] = ColumnHasAnchor(Source, X);
	}

	if(std::none_of(vInterestingColumns.begin(), vInterestingColumns.end(), [](bool Value) { return Value; }))
	{
		std::fill(vInterestingColumns.begin(), vInterestingColumns.end(), true);
	}

	for(int X = 0; X < Source.m_GameLayer.m_Width; ++X)
	{
		if(vAnchorColumns[X])
			vInterestingColumns[X] = true;
	}

	std::vector<bool> vDilated = vInterestingColumns;
	for(int X = 0; X < Source.m_GameLayer.m_Width; ++X)
	{
		if(!vInterestingColumns[X])
			continue;
		if(X > 0)
			vDilated[X - 1] = true;
		if(X + 1 < Source.m_GameLayer.m_Width)
			vDilated[X + 1] = true;
	}

	std::vector<CColumnSegment> vSegments;
	for(int X = 0; X < Source.m_GameLayer.m_Width; ++X)
	{
		if(!vDilated[X])
			continue;
		CColumnSegment Segment;
		Segment.m_Start = X;
		while(X + 1 < Source.m_GameLayer.m_Width && vDilated[X + 1])
			++X;
		Segment.m_End = X;
		for(int Column = Segment.m_Start; Column <= Segment.m_End; ++Column)
			Segment.m_HasAnchor = Segment.m_HasAnchor || vAnchorColumns[Column];
		vSegments.push_back(Segment);
	}
	return vSegments;
}

std::vector<CColumnSegment> ChooseSegmentsToKeep(const std::vector<CColumnSegment> &vSegments, int KeepEvery)
{
	if(vSegments.empty())
		return {};
	if(vSegments.size() <= 2)
		return vSegments;

	std::vector<CColumnSegment> vKept;
	int MiddleSegmentCounter = 0;
	for(size_t Index = 0; Index < vSegments.size(); ++Index)
	{
		const bool IsEdge = Index == 0 || Index + 1 == vSegments.size();
		bool Keep = IsEdge || vSegments[Index].m_HasAnchor;
		if(!Keep)
		{
			Keep = (MiddleSegmentCounter % KeepEvery) == 0;
			++MiddleSegmentCounter;
		}
		if(Keep)
			vKept.push_back(vSegments[Index]);
	}

	return vKept;
}

int ChooseGapWidth(const std::vector<CColumnSegment> &vSegments, int GapExtra)
{
	int TotalGap = 0;
	int GapCount = 0;
	for(size_t Index = 1; Index < vSegments.size(); ++Index)
	{
		const int Gap = vSegments[Index].m_Start - vSegments[Index - 1].m_End - 1;
		if(Gap > 0)
		{
			TotalGap += Gap;
			++GapCount;
		}
	}

	const int AverageGap = GapCount > 0 ? (TotalGap + GapCount / 2) / GapCount : 3;
	return std::max(6, AverageGap + GapExtra);
}

void OverlaySegment(std::vector<CTile> &vDestination, int DestinationWidth, int Height, const CTileLayerData &SourceLayer, const CColumnSegment &Segment, int DestinationStart)
{
	for(int SourceX = Segment.m_Start; SourceX <= Segment.m_End; ++SourceX)
	{
		const int DestinationX = DestinationStart + (SourceX - Segment.m_Start);
		for(int Y = 0; Y < Height; ++Y)
			SetTile(vDestination, DestinationWidth, Height, DestinationX, Y, GetTile(SourceLayer, SourceX, Y));
	}
}

bool HasAnyTiles(const std::vector<CTile> &vTiles)
{
	return std::any_of(vTiles.begin(), vTiles.end(), [](const CTile &Tile) { return !IsAir(Tile); });
}

void ApplySourceMetadataDefaults(const CSourceMapData &Source, CGeneratorConfig &Config)
{
	if(Config.m_Author == DEFAULT_AUTHOR && !Source.m_Author.empty())
		Config.m_Author = Source.m_Author;
	if(Config.m_MapVersion == DEFAULT_MAP_VERSION && !Source.m_MapVersion.empty())
		Config.m_MapVersion = Source.m_MapVersion + "-short";
	if(Config.m_License == DEFAULT_LICENSE && !Source.m_License.empty())
		Config.m_License = Source.m_License;
	if(Config.m_Credits == DEFAULT_CREDITS)
	{
		char aCredits[512];
		str_format(aCredits, sizeof(aCredits), "Shortened from %s with wider gaps", fs_filename(Config.m_SourceMapPath.c_str()));
		Config.m_Credits = aCredits;
	}
}

bool WriteGameOnlyMap(IStorage &Storage, const CGeneratorConfig &Config, const std::vector<CTile> &vGameTiles, const std::vector<CTile> *pFrontTiles, int Width, int Height, const char *pGameLayerName, const char *pFrontLayerName)
{
	const int StorageType = IsAbsolutePath(Config.m_OutputPath.c_str()) ? IStorage::TYPE_ABSOLUTE : IStorage::TYPE_SAVE;
	char aFullPath[IO_MAX_PATH_LENGTH];
	if(!PrepareOutputPath(Storage, Config.m_OutputPath.c_str(), StorageType, aFullPath, sizeof(aFullPath)))
		return false;

	CDataFileWriter Writer;
	if(!Writer.Open(&Storage, Config.m_OutputPath.c_str(), StorageType))
	{
		log_error(TOOL_NAME, "Failed to open '%s' for writing", aFullPath);
		return false;
	}

	CMapItemVersion VersionItem{};
	VersionItem.m_Version = 1;
	Writer.AddItem(MAPITEMTYPE_VERSION, 0, sizeof(VersionItem), &VersionItem);

	CMapItemInfoSettings InfoItem{};
	InfoItem.m_Version = 1;
	InfoItem.m_Author = Writer.AddDataString(Config.m_Author.c_str());
	InfoItem.m_MapVersion = Writer.AddDataString(Config.m_MapVersion.c_str());
	InfoItem.m_Credits = Writer.AddDataString(Config.m_Credits.c_str());
	InfoItem.m_License = Writer.AddDataString(Config.m_License.c_str());
	InfoItem.m_Settings = -1;
	Writer.AddItem(MAPITEMTYPE_INFO, 0, sizeof(InfoItem), &InfoItem);

	const int GameLayerData = Writer.AddData(vGameTiles.size() * sizeof(CTile), vGameTiles.data());
	const bool HasFrontLayer = pFrontTiles != nullptr && HasAnyTiles(*pFrontTiles);
	std::vector<CTile> vEmptyTiles;
	int FrontEmptyData = -1;
	int FrontLayerData = -1;
	if(HasFrontLayer)
	{
		vEmptyTiles.assign((size_t)Width * Height, MakeTile(TILE_AIR));
		FrontEmptyData = Writer.AddData(vEmptyTiles.size() * sizeof(CTile), vEmptyTiles.data());
		FrontLayerData = Writer.AddData(pFrontTiles->size() * sizeof(CTile), pFrontTiles->data());
	}

	int LayerId = 0;
	CMapItemLayerTilemap GameLayer{};
	GameLayer.m_Layer.m_Version = 0;
	GameLayer.m_Layer.m_Type = LAYERTYPE_TILES;
	GameLayer.m_Layer.m_Flags = 0;
	GameLayer.m_Version = 3;
	GameLayer.m_Width = Width;
	GameLayer.m_Height = Height;
	GameLayer.m_Flags = TILESLAYERFLAG_GAME;
	GameLayer.m_Color = CColor(255, 255, 255, 255);
	GameLayer.m_ColorEnv = -1;
	GameLayer.m_ColorEnvOffset = 0;
	GameLayer.m_Image = -1;
	GameLayer.m_Data = GameLayerData;
	StrToInts(GameLayer.m_aName, std::size(GameLayer.m_aName), pGameLayerName && pGameLayerName[0] ? pGameLayerName : GAME_LAYER_NAME);
	GameLayer.m_Tele = -1;
	GameLayer.m_Speedup = -1;
	GameLayer.m_Front = -1;
	GameLayer.m_Switch = -1;
	GameLayer.m_Tune = -1;
	Writer.AddItem(MAPITEMTYPE_LAYER, LayerId++, sizeof(GameLayer), &GameLayer);

	if(HasFrontLayer)
	{
		CMapItemLayerTilemap FrontLayer{};
		FrontLayer.m_Layer.m_Version = 0;
		FrontLayer.m_Layer.m_Type = LAYERTYPE_TILES;
		FrontLayer.m_Layer.m_Flags = 0;
		FrontLayer.m_Version = 3;
		FrontLayer.m_Width = Width;
		FrontLayer.m_Height = Height;
		FrontLayer.m_Flags = TILESLAYERFLAG_FRONT;
		FrontLayer.m_Color = CColor(255, 255, 255, 255);
		FrontLayer.m_ColorEnv = -1;
		FrontLayer.m_ColorEnvOffset = 0;
		FrontLayer.m_Image = -1;
		FrontLayer.m_Data = FrontEmptyData;
		StrToInts(FrontLayer.m_aName, std::size(FrontLayer.m_aName), pFrontLayerName && pFrontLayerName[0] ? pFrontLayerName : FRONT_LAYER_NAME);
		FrontLayer.m_Tele = -1;
		FrontLayer.m_Speedup = -1;
		FrontLayer.m_Front = FrontLayerData;
		FrontLayer.m_Switch = -1;
		FrontLayer.m_Tune = -1;
		Writer.AddItem(MAPITEMTYPE_LAYER, LayerId++, sizeof(FrontLayer), &FrontLayer);
	}

	CMapItemGroup GameGroup{};
	GameGroup.m_Version = 3;
	GameGroup.m_OffsetX = 0;
	GameGroup.m_OffsetY = 0;
	GameGroup.m_ParallaxX = 100;
	GameGroup.m_ParallaxY = 100;
	GameGroup.m_StartLayer = 0;
	GameGroup.m_NumLayers = LayerId;
	GameGroup.m_UseClipping = 0;
	GameGroup.m_ClipX = 0;
	GameGroup.m_ClipY = 0;
	GameGroup.m_ClipW = 0;
	GameGroup.m_ClipH = 0;
	StrToInts(GameGroup.m_aName, std::size(GameGroup.m_aName), GROUP_NAME);
	Writer.AddItem(MAPITEMTYPE_GROUP, 0, sizeof(GameGroup), &GameGroup);

	Writer.Finish();
	log_info(TOOL_NAME, "Generated map: %s", aFullPath);
	return true;
}

bool WriteSkeletonMap(const CGeneratorConfig &Config, IStorage &Storage)
{
	std::vector<CTile> vGameLayerTiles = CreateGameLayerTiles(Config);
	if(!WriteGameOnlyMap(Storage, Config, vGameLayerTiles, nullptr, Config.m_Width, Config.m_Height, GAME_LAYER_NAME, FRONT_LAYER_NAME))
		return false;

	log_info(TOOL_NAME, "Layout: %dx%d, spawn=(2,%d), start=(3,%d), finish=(%d,%d)",
		Config.m_Width, Config.m_Height,
		Config.m_Height - 2, Config.m_Height - 2,
		Config.m_Width - 4, Config.m_Height - 2);
	return true;
}

bool WriteShortenedSourceMap(CGeneratorConfig Config, IStorage &Storage)
{
	CSourceMapData Source;
	if(!LoadSourceMap(Config, Storage, Source))
		return false;

	ApplySourceMetadataDefaults(Source, Config);

	const CAnchorInfo Anchors = FindAnchors(Source);
	const EProgressAxis Axis = DetectProgressAxis(Source, Anchors);
	const std::vector<bool> vBaselineCrossLines = DetectBaselineCrossLines(Source, Axis);
	const std::vector<CColumnSegment> vSegments = FindObstacleSegmentsOnAxis(Source, Axis, vBaselineCrossLines);
	if(vSegments.empty())
	{
		log_error(TOOL_NAME, "Could not detect any obstacle segments in source map");
		return false;
	}

	const std::vector<CColumnSegment> vKeptSegments = ChooseSegmentsToKeep(vSegments, Config.m_KeepEvery);
	const int GapWidth = ChooseGapWidth(vSegments, Config.m_GapExtra);
	const int NewMainLength = 2 + std::accumulate(vKeptSegments.begin(), vKeptSegments.end(), 0, [](int Sum, const CColumnSegment &Segment) {
		return Sum + Segment.Width();
	}) + std::max(0, (int)vKeptSegments.size() - 1) * GapWidth + 2;
	const int OutputWidth = Axis == EProgressAxis::Horizontal ? NewMainLength : Source.m_GameLayer.m_Width;
	const int OutputHeight = Axis == EProgressAxis::Horizontal ? Source.m_GameLayer.m_Height : NewMainLength;

	std::vector<CTile> vNewGameTiles = BuildBaselineFillOnAxis(Source.m_GameLayer, Axis, NewMainLength, OutputWidth, OutputHeight, vBaselineCrossLines);
	std::optional<std::vector<CTile>> vNewFrontTiles;
	if(Source.m_FrontLayer.m_Present)
		vNewFrontTiles = BuildBaselineFillOnAxis(Source.m_FrontLayer, Axis, NewMainLength, OutputWidth, OutputHeight, vBaselineCrossLines);

	int DestinationMain = 2;
	for(const CColumnSegment &Segment : vKeptSegments)
	{
		OverlayAxisSegment(vNewGameTiles, OutputWidth, OutputHeight, Source.m_GameLayer, Axis, Segment, DestinationMain);
		if(vNewFrontTiles.has_value())
			OverlayAxisSegment(*vNewFrontTiles, OutputWidth, OutputHeight, Source.m_FrontLayer, Axis, Segment, DestinationMain);
		DestinationMain += Segment.Width() + GapWidth;
	}

	if(!WriteGameOnlyMap(Storage, Config, vNewGameTiles, vNewFrontTiles ? &*vNewFrontTiles : nullptr, OutputWidth, OutputHeight,
		Source.m_GameLayer.m_Name.c_str(), Source.m_FrontLayer.m_Name.c_str()))
		return false;

	log_info(TOOL_NAME, "Source layout: %dx%d", Source.m_GameLayer.m_Width, Source.m_GameLayer.m_Height);
	log_info(TOOL_NAME, "Progress axis: %s", Axis == EProgressAxis::Horizontal ? "horizontal" : "vertical");
	if(Anchors.m_Start.has_value())
		log_info(TOOL_NAME, "Start anchor: (%d,%d)", Anchors.m_Start->x, Anchors.m_Start->y);
	if(Anchors.m_Finish.has_value())
		log_info(TOOL_NAME, "Finish anchor: (%d,%d)", Anchors.m_Finish->x, Anchors.m_Finish->y);
	log_info(TOOL_NAME, "Shortened layout: %dx%d", OutputWidth, OutputHeight);
	log_info(TOOL_NAME, "Detected %d obstacle chunks, kept %d, widened gaps to %d columns",
		(int)vSegments.size(), (int)vKeptSegments.size(), GapWidth);
	return true;
}
} // namespace

int RunMapGenerator(int argc, const char **argv)
{
	CGeneratorConfig Config;
	switch(ParseArguments(argc, argv, Config))
	{
	case EParseResult::Success:
		break;
	case EParseResult::Help:
		return 0;
	case EParseResult::Error:
		return -1;
	}

	std::unique_ptr<IStorage> pStorage(CreateStorage(IStorage::EInitializationType::BASIC, argc, argv));
	if(!pStorage)
	{
		log_error(TOOL_NAME, "Error creating basic storage");
		return -1;
	}

	if(!Config.m_SourceMapPath.empty())
		return WriteShortenedSourceMap(Config, *pStorage) ? 0 : -1;
	return WriteSkeletonMap(Config, *pStorage) ? 0 : -1;
}
