#include <game/client/components/skins.h>
#include <game/client/render.h>

#include <gtest/gtest.h>

TEST(SkinsPreviewLayers, FlagsAreDistinctBits)
{
	EXPECT_NE(TEE_PREVIEW_LAYER_BODY_OUTLINE, TEE_PREVIEW_LAYER_BODY);
	EXPECT_NE(TEE_PREVIEW_LAYER_BACK_FEET_OUTLINE, TEE_PREVIEW_LAYER_BACK_FEET);
	EXPECT_NE(TEE_PREVIEW_LAYER_FRONT_FEET_OUTLINE, TEE_PREVIEW_LAYER_FRONT_FEET);
	EXPECT_NE(TEE_PREVIEW_LAYER_OUTLINE, TEE_PREVIEW_LAYER_BODY);
	EXPECT_NE(TEE_PREVIEW_LAYER_BODY, TEE_PREVIEW_LAYER_FEET);
	EXPECT_NE(TEE_PREVIEW_LAYER_FEET, TEE_PREVIEW_LAYER_EYES);
}

TEST(SkinsPreviewLayers, ZeroMaskResolvesToAllLayers)
{
	EXPECT_EQ(ResolveTeePreviewLayers(0), TEE_PREVIEW_LAYER_ALL);
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_OUTLINE));
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_BODY_OUTLINE));
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_BACK_FEET_OUTLINE));
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_FRONT_FEET_OUTLINE));
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_BODY));
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_FEET));
	EXPECT_TRUE(HasTeePreviewLayer(0, TEE_PREVIEW_LAYER_EYES));
}

TEST(SkinsPreviewLayers, ExplicitMaskSelectsOnlyRequestedFillLayers)
{
	const int Mask = TEE_PREVIEW_LAYER_BODY | TEE_PREVIEW_LAYER_FEET;
	EXPECT_TRUE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_BODY));
	EXPECT_TRUE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_FEET));
	EXPECT_FALSE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_OUTLINE));
	EXPECT_FALSE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_EYES));
}

TEST(SkinsPreviewLayers, OutlineMaskDoesNotSelectFillLayers)
{
	const int Mask = TEE_PREVIEW_LAYER_BODY_OUTLINE | TEE_PREVIEW_LAYER_BACK_FEET_OUTLINE;
	EXPECT_TRUE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_BODY_OUTLINE));
	EXPECT_TRUE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_BACK_FEET_OUTLINE));
	EXPECT_FALSE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_BODY));
	EXPECT_FALSE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_BACK_FEET));
	EXPECT_FALSE(HasTeePreviewLayer(Mask, TEE_PREVIEW_LAYER_FRONT_FEET_OUTLINE));
}
