[workspace]
members = [
  "src/base",
  "src/engine",
  "src/engine/shared",
  "src/qm-update",
  "src/rust-bridge/test",
]

resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
lto = "thin"
panic = "abort"

[profile.relwithdebinfo]
inherits = "release"
debug = true

[profile.minsizerel]
inherits = "release"
opt-level = "z"
